# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'HelloSud-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YYText', '~> 1.0.7'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.4.1'
  pod 'MJRefresh', '3.7.5'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Bugly', '2.5.90'
  pod 'SDWebImage', '5.12.2'
  pod 'SDWebImageWebPCoder'
  pod 'SVGAPlayer', :git =>'https://github.com/svga/SVGAPlayer-iOS.git', :tag => '2.5.6'
  pod 'lottie-ios', '~> 2.5.3'
  pod 'BDAlphaPlayer', '~> 1.2.0'
  pod 'IQKeyboardManager', '~> 6.5.9'
  # 跑马灯
  pod 'MarqueeLabel'
  # RTC厂商引入
  # zego语音SDK
  pod 'ZegoExpressEngine/Audio', '~> 2.17.0'
  # agora语音SDK
  pod 'AgoraAudio_iOS', '3.6.1.1'
  # agora云信令SDK
  pod 'AgoraRtm_iOS', '1.4.9'
  # rongcloud音频SDK
  pod 'RCVoiceRoomLib', '~> 2.0.7'
  # netease 语音SDK
  pod 'NERtcSDK', '~> 4.6.0'
  # netease IM SDK
  pod 'NIMSDK_LITE', '9.0.1'
end

