# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'HelloSud-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YYText', '~> 1.0.7'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.4.1'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'ZegoExpressEngine/Audio', '~> 2.15.0'
  pod 'Bugly', '2.5.90'
  pod 'SDWebImage', '5.12.2'
  pod 'SVGAPlayer', :git =>'https://github.com/svga/SVGAPlayer-iOS.git', :tag => '2.5.6'

end

