# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "正在构建HelloSudPlus-iOS版本"

  SCHEME_NAME = "HelloSud-iOS"
  VERSION_NUM = "1.0.0"  
  OUTPUT_DIR = "../build/#{ENV['CI_BUILD_ID']}"
  OUTPUT_DYSM_DIR = "../#{OUTPUT_DIR}"
  TEST_OUTPU_DIR = "../build/iOSBuild"
  TEST_DYSM_DIR="../#{TEST_OUTPU_DIR}"
  RESULT_PRE_NAME = "HelloSud-iOS-#{ENV['CI_BUILD_ID']}"
  DYSM_LOAD_PATH = "#{RESULT_PRE_NAME}-dSYM"
  DYSM_NAME = "#{RESULT_PRE_NAME}.app.dSYM"
  IPA_NAME = "#{RESULT_PRE_NAME}.ipa"

  before_all do
    cocoapods(clean_install: true, podfile:"./Podfile")
  end

  lane :buildHeader do
    increment_build_number(build_number: ENV['CI_BUILD_ID'])
    unlock_keychain(
      path: "/Users/packagemini/Library/Keychains/login.keychain-db",
      password: "divtossABC"
    )
  end

  lane :buildFooter do
    # echo "footer"
  end

  lane :buildDebugIOS do
    # add actions here: https://docs.fastlane.tools/actions
    buildHeader
    build_app(
      clean: true,
      include_symbols: true,
      scheme: "HelloSud-iOS",
      workspace: "HelloSud-iOS.xcworkspace",
      include_bitcode: false,
      configuration: "Debug",
      export_options: {
        method: "development",
        provisioningProfiles: {
          "tech.sud.mgp.hello" => "Dev_Sud_MGP"
        }
      },
      xcargs: "-allowProvisioningUpdates",
      output_directory: TEST_OUTPU_DIR,
      output_name: IPA_NAME
    )
    # 上传符号表到bugly
    sh("unzip -d #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH} #{TEST_DYSM_DIR}/#{DYSM_NAME}.zip")
    sh("mkdir #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    sh("mv #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud.app.dSYM #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    sh("pwd")
    sh("java -version")
    sh("java -jar ../../tool/buglyqq-upload-symbol.jar -appid 0d680b2d4c -appkey fdea2fe7-9b55-48fe-9d14-eb294dd1c4df -bundleid tech.sud.mgp.hello -version #{VERSION_NUM}.#{ENV['CI_BUILD_ID']} -platform IOS -inputSymbol #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    buildFooter
  end

  lane :buildReleaseIOS do
    # add actions here: https://docs.fastlane.tools/actions
    buildHeader
    build_app(
      clean: true,
      include_symbols: true,
      scheme: "HelloSud-iOS",
      workspace: "HelloSud-iOS.xcworkspace",
      include_bitcode: false,
      configuration: "Release",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "tech.sud.mgp.hello" => "Dis_Tech_Sud_Mgp_Hello"
        }
      },
      xcargs: "-allowProvisioningUpdates",
      output_directory: TEST_OUTPU_DIR,
      output_name: IPA_NAME
    )
    # 上传符号表到bugly
    sh("unzip -d #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH} #{TEST_DYSM_DIR}/#{DYSM_NAME}.zip")
    sh("mkdir #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    sh("mv #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud.app.dSYM #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    sh("pwd")
    sh("java -version")
    sh("java -jar ../../tool/buglyqq-upload-symbol.jar -appid 8385698b84 -appkey 1010766c-9314-490c-8be3-e153c0bfba6f -bundleid tech.sud.mgp.hello -version #{VERSION_NUM}.#{ENV['CI_BUILD_ID']} -platform IOS -inputSymbol #{TEST_DYSM_DIR}/#{DYSM_LOAD_PATH}/HelloSud-app-dSYM")
    buildFooter
  end
end
