# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'QuickStartSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SudMGP_Lite', '1.4.9'
  pod 'SudMGPWrapper_Lite'
  pod 'SnapKit'
end

