# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/volcengine/volcengine-specs.git’

inhibit_all_warnings!

target 'HelloSudPlus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 富文本
  #  pod 'YYText', '~> 1.0.7'
  # fixed xcode 15接口废弃引擎奔溃问题
  pod 'YYText', :git =>'https://github.com/kaniel520/YYText.git', :tag => '1.0.9'
  # 自动布局
  pod 'Masonry', '~> 1.1.0'
  # json序列化
  pod 'MJExtension', '~> 3.4.1'
  # 下拉刷新
  pod 'MJRefresh', '3.7.5'
  # Http网络请求库
  pod 'AFNetworking', '~> 4.0.1'
  # Toast
  pod 'SVProgressHUD', '~> 2.2.5'
  # 异常追踪
  pod 'Bugly', '2.5.90'
  # 图片加载
  pod 'SDWebImage', '5.12.2'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImageSVGKitPlugin', '1.4.0'
  # SVGA动画库
  pod 'SVGAPlayer', :git =>'https://github.com/svga/SVGAPlayer-iOS.git', :tag => '2.5.6'
  # lottie动画库
  pod 'lottie-ios', '~> 2.5.3'
  # mp4格式动画库
  pod 'BDAlphaPlayer', '~> 1.2.0'
  # 键盘管理
  pod 'IQKeyboardManager', '~> 6.5.9'
  # 导航分类
  pod 'JXCategoryView', '~> 1.5.9'
  # 跑马灯
  pod 'MarqueeLabel'
  # 日志
  pod 'CocoaLumberjack'
  # RTC厂商引入
  # zego语音/视频SDK
  pod 'ZegoExpressEngine', '~> 3.20.2'
  # zego IM SDK
  pod 'ZIM', '~> 2.20.0'
  # agora语音SDK
  pod 'AgoraRtcEngine_iOS', '4.2.6'
  # agora云信令SDK
  pod 'AgoraRtm_iOS', '2.2.1'
  # rongcloud音频SDK
  pod 'RCVoiceRoomLib', '~> 2.0.7'
  # netease 语音SDK
  pod 'NERtcSDK', '~> 5.8.15'
  # netease IM SDK
  pod 'NIMSDK_LITE', '~> 10.8.30'
  # volc火山引擎SDK
  pod 'VolcEngineRTC', '~> 3.50.308' ,:source => 'https://github.com/volcengine/volcengine-specs.git'
  # tx腾讯云SDK
  #pod 'TXLiteAVSDK_TRTC', :podspec => 'https://liteav.sdk.qcloud.com/pod/liteavsdkspec/TXLiteAVSDK_TRTC.podspec'
  pod 'TXLiteAVSDK_TRTC', '~> 10.2.11418'
  # SudMGP包装类
    pod 'SudGIPWrapper', :path => '../../'
  # 标准版（不支持部分游戏，包体较小）
#  pod 'SudGIP', '~> 1.6.1'
#  pod 'SudGIPWrapper'
  
  # pro版本（支持全部游戏，包体会大一些）
#  pod 'SudGIP-pro', '~> 1.6.1'
#  pod 'SudGIPWrapper-pro'
# 语音识别
pod 'SudASR', :path => '../../'
#  pod 'SudASR'
# 最基本，不包含微软
#pod 'SudASR/Base', :path => '../../'
#  pod 'SudASR/Base'
  # SudNFT SDK
  pod 'SudNFT', '1.0.5'
  # 分页点
  #  pod 'XHPageControl'
  pod 'Protobuf', '3.22.3'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      #      config.build_settings['ARCHS'] = 'arm64'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # 14.3版本xcode编译问题
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
  
  
#  #移除三方库BitCode
#  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
# 
#  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
#    framework_path = File.join(Dir.pwd, framework_relative_path)
#    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
#    puts "Stripping bitcode: #{command}"
#    system(command)
#  end
# 
#  framework_paths = [
#    "Pods/NERtcAiDenoise.framework/NERtcAiDenoise",
#    "Pods/NERtcAiHowling.framework/NERtcAiHowling",
#    "Pods/NERtcBeauty.framework/NERtcBeauty",
#    "Pods/NERtcFaceDetect.framework/NERtcFaceDetect",
#    "Pods/NERtcPersonSegment.framework/NERtcPersonSegment",
#    "Pods/NERtcReplayKit.framework/NERtcReplayKit",
#    "Pods/NERtcSDK.framework/NERtcSDK",
#    "Pods/NERtcnn.framework/NERtcnn",
#
#    "Pods/NIMSDK.framework/NIMSDK",
#    "Pods/RongRTCLib.framework/RongRTCLib",
#    "Pods/SudNFT.framework/SudNFT",
#    "Pods/ZIM.framework/ZIM",
#    "Pods/ZegoExpressEngine.framework/ZegoExpressEngine",
#  ]
# 
#  framework_paths.each do |framework_relative_path|
#    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
#  end
end

