# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'HelloSudPlus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 富文本
#  pod 'YYText', '~> 1.0.7'
  # fixed xcode 15接口废弃引擎奔溃问题
  pod 'YYText', :git =>'https://github.com/kaniel520/YYText.git', :tag => '1.0.9'
  # 自动布局
  pod 'Masonry', '~> 1.1.0'
  # json序列化
  pod 'MJExtension', '~> 3.4.1'
  # 下拉刷新
  pod 'MJRefresh', '3.7.5'
  # Http网络请求库
  pod 'AFNetworking', '~> 4.0.1'
  # Toast
  pod 'SVProgressHUD', '~> 2.2.5'
  # 异常追踪
  pod 'Bugly', '2.5.90'
  # 图片加载
  pod 'SDWebImage', '5.12.2'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImageSVGKitPlugin', '1.4.0'
  # SVGA动画库
  pod 'SVGAPlayer', :git =>'https://github.com/svga/SVGAPlayer-iOS.git', :tag => '2.5.6'
  # lottie动画库
  pod 'lottie-ios', '~> 2.5.3'
  # mp4格式动画库
  pod 'BDAlphaPlayer', '~> 1.2.0'
  # 键盘管理
  pod 'IQKeyboardManager', '~> 6.5.9'
  # 导航分类
  pod 'JXCategoryView', '~> 1.5.9'
  # 跑马灯
  pod 'MarqueeLabel'
  # 日志
  pod 'CocoaLumberjack'
  # RTC厂商引入
  # zego语音/视频SDK
  pod 'ZegoExpressEngine', '2.17.1.1'
  # zego IM SDK
  pod 'ZIM', '2.4.2'
  # agora语音SDK
  pod 'AgoraRtcEngine_iOS', '4.2.6'
  # agora云信令SDK
  pod 'AgoraRtm_iOS', '1.4.9'
  # rongcloud音频SDK
  pod 'RCVoiceRoomLib', '~> 2.0.7'
  # netease 语音SDK
  pod 'NERtcSDK', '~> 4.6.0'
  # netease IM SDK
  pod 'NIMSDK_LITE', '9.0.1'
  # volc火山引擎SDK
   pod 'VolcEngineRTC', '3.37.101' ,:source => 'https://github.com/volcengine/volcengine-specs.git'
#  pod 'VolcEngineRTC', '3.37.101'
  # tx腾讯云SDK
  #pod 'TXLiteAVSDK_TRTC', :podspec => 'https://liteav.sdk.qcloud.com/pod/liteavsdkspec/TXLiteAVSDK_TRTC.podspec'
  pod 'TXLiteAVSDK_TRTC', '10.2.11418'
  # SudMGP包装类
  #pod 'SudMGPWrapper', :path => '../../'
  # 标准版（支持全部游戏，包体会大一些）
  pod 'SudMGPWrapper', '~> 1.3.6.1'
  # 轻量版（不支持部分游戏，包体较小）
#  pod 'SudMGPWrapper_Lite', '~> 1.3.6.1'
  # SudNFT SDK
  pod 'SudNFT', '1.0.4'
  #使用ASR时集成该库
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.23.0'
  # 分页点
#  pod 'XHPageControl'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
#      config.build_settings['ARCHS'] = 'arm64'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # 14.3版本xcode编译问题
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

