platform :ios, '11.0'
use_frameworks!

target 'QuickStart-Runtime' do
  pod 'Masonry'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SudGIP', :path => '../../'
end

post_install do |installer|
    # disable ENABLE_BITCODE
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
end
