# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

# QuickStart
target 'QuickStart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 富文本
#  pod 'YYText', '~> 1.0.7'
  # 1.0.9
  pod 'YYText', :git =>'https://github.com/kaniel520/YYText.git', :tag => '1.0.9'
  # 自动布局
  pod 'Masonry', '~> 1.1.0'
  # json序列化
  pod 'MJExtension', '~> 3.4.1'
  # 下拉刷新
  pod 'MJRefresh', '3.7.5'
  # Http网络请求库
  pod 'AFNetworking', '~> 4.0.1'
  # Toast
  pod 'SVProgressHUD', '~> 2.2.5'
  # 图片加载
  pod 'SDWebImage', '5.12.2'
  # 键盘管理
  pod 'IQKeyboardManager', '~> 6.5.9'
  # 跑马灯
  pod 'MarqueeLabel'
  # 日志
  pod 'CocoaLumberjack'
  # SudMGPSDK包装类
  # 标准版（支持全部游戏，包体会大一些）最新版本号请参阅：https://github.com/SudTechnology/sud-mgp-ios
  # Standard version (support all game, package experience larger) the latest version, please refer to: https://github.com/SudTechnology/sud-mgp-ios/blob/main/README_en.md
  pod 'SudMGPWrapper', '~> 1.3.6.1'
  # 轻量版（不支持部分游戏，包体较小）最新版本版本号请参阅：https://github.com/SudTechnology/sud-mgp-ios
  # Lightweight version (does not support some of the games, small inclusions) the latest version of the version number, please refer to: https://github.com/SudTechnology/sud-mgp-ios/blob/main/README_en.md
#  pod 'SudMGPWrapper_Lite', '~> 1.3.6.1'
#  pod 'SudMGPWrapper', :path => '../../'
end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
#      config.build_settings['ARCHS'] = 'arm64'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # 14.3版本xcode编译问题
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

